sources:
  - name: FOAF
    handler:
      "@inrupt/experimental-graphql-introspection-ontology":
        # Note - if this link is broken a build failure will occur
        source: https://web.archive.org/web/20220614105937if_/http://xmlns.com/foaf/spec/20140114.rdf
