name: CI

on: [push]

env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Note - we exclude node 14 since npm ci fails on git dependencies
        # see https://github.com/inrupt/experimental-solid-graphql-js/actions/runs/3390977682/jobs/5635685354
        node-version: ["18", "16"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run test

      # Sonar analysis needs the full history for features like automatic assignment of bugs. If the following step
      # is not included the project will show a warning about incomplete information.
      - run: git fetch --unshallow
        if: ${{ matrix.node-version == '18' }}

      # Since this is a monorepo, the Sonar scan must be run on each of the packages but this will pull in the test
      # coverage information produced by the tests already run.
      # - name: SonarCloud Scan - Solid Directives
      #   if: ${{ matrix.node-version == '18' && github.actor != 'dependabot[bot]'}}
      #   uses: SonarSource/sonarcloud-github-action@v1.7
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     projectBaseDir: packages/directives/solid
